"""Turn an interview into advice the officer can act on.

Everything here is derived arithmetically from what was measured. Nothing is
generated by a model, for two reasons: a language model asked to write
"strengths and weaknesses" produces fluent encouragement whether or not the
evidence supports it, and an officer who spots one invented strength stops
believing the rest of the report.

So each item below names the number it came from. If a claim cannot point at a
measurement, it is not made.
"""

from __future__ import annotations

from dataclasses import dataclass, field

# Axis thresholds on the 1-5 scale.
STRONG = 4.0
WEAK = 2.5

# Speech thresholds. Wide, because these are coaching hints rather than
# findings, and a narrow band would flag ordinary speech as a problem.
FAST_WPM = 175.0
SLOW_WPM = 95.0
HIGH_FILLER_RATE = 8.0      # per 100 words
LONG_PAUSE_CONCERN = 4

# Above this a competency is not worth putting on a practice list. Not the
# same as WEAK: something answered at L3 is worth another go, but something
# answered at L4 is not, however it ranks against the rest of the session.
PRACTICE_CEILING = 3.5


@dataclass
class Coaching:
    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    practice: list[str] = field(default_factory=list)
    # Competency ids the officer should be shown courses for, widest gap first.
    focus_competency_ids: list[int] = field(default_factory=list)


AXIS_STRENGTH = {
    "knowledge": "The substance was there — your answers covered what the rubric expected.",
    "structure": "Your answers had a clear line of reasoning from start to finish.",
    "communication": "You explained ideas in a way a colleague outside your specialism could follow.",
    "fluency": "Your delivery held steady against your own calibration baseline.",
    "confidence": "You committed to your answers rather than hedging them.",
}

AXIS_WEAKNESS = {
    "knowledge": "Several answers did not reach the points the question was looking for.",
    "structure": "Answers tended to arrive at the point rather than lead with it.",
    "communication": "Terms went undefined, which makes an answer hard to follow for anyone outside the subject.",
    "fluency": "Delivery drifted from your own baseline — not a competence signal, but worth knowing.",
    "confidence": "Hedging language and long hesitations were frequent enough to notice.",
}

AXIS_SUGGESTION = {
    "knowledge": "Work the competencies listed below before re-attempting. An assessment after a course is what actually moves your profile.",
    "structure": "Try answering in three moves: the direct answer, then why, then an example. Rehearse one aloud before recording.",
    "communication": "Define the technical term the first time you use it, as though briefing someone from another division.",
    "fluency": "Nothing to fix here on its own. If you want the number to move, rehearsing the answer aloud once first is what changes it.",
    "confidence": "Where you are sure, say so plainly. Where you are not, saying 'I would check X' reads as judgement, not hesitation.",
}


def build_coaching(report: dict, gaps: list | None = None) -> Coaching:
    """Assemble strengths, weaknesses and next steps from a built report.

    Takes the report `build_report` already produced rather than re-querying, so
    the advice cannot disagree with the numbers printed next to it.
    """
    coaching = Coaching()
    axes = report.get("axes") or {}

    for key, axis in axes.items():
        average = (axis or {}).get("score")
        if average is None:
            continue
        if average >= STRONG and key in AXIS_STRENGTH:
            coaching.strengths.append(AXIS_STRENGTH[key])
        elif average <= WEAK and key in AXIS_WEAKNESS:
            coaching.weaknesses.append(AXIS_WEAKNESS[key])
            coaching.suggestions.append(AXIS_SUGGESTION[key])

    # Points the officer missed, gathered across answers. More useful than an
    # axis average because it names the specific thing.
    missed: dict[str, int] = {}
    covered_total = 0
    for answer in report.get("answers") or []:
        for point in answer.get("missed_points") or []:
            missed[str(point)] = missed.get(str(point), 0) + 1
        covered_total += len(answer.get("covered_points") or [])

    for point, count in sorted(missed.items(), key=lambda kv: -kv[1])[:4]:
        coaching.weaknesses.append(
            f"Not addressed: {point}" + (f" (came up {count} times)" if count > 1 else "")
        )

    if covered_total and not coaching.strengths:
        coaching.strengths.append(
            f"You covered {covered_total} of the points the rubric was looking for."
        )

    # Speech observations, kept separate from competency advice and labelled as
    # delivery so they are not read as knowledge findings.
    speech = _speech_observations(report)
    coaching.suggestions.extend(speech)

    # What to practise. Ranked weakest first, but only competencies that were
    # actually weak: with two competencies in a session, taking the bottom three
    # means recommending the officer re-attempt the one they did best at, which
    # is how a coaching report stops being read.
    ranked = [row for row in _weakest_raw(report) if row[2] < PRACTICE_CEILING]
    for _, name, level in ranked[:3]:
        if name:
            coaching.practice.append(
                f"Re-attempt {name}: answered at around L{level:.1f} in this session."
            )
    coaching.focus_competency_ids = [cid for cid, _, _ in ranked][:3]

    if not coaching.weaknesses:
        coaching.weaknesses.append(
            "Nothing stood out as weak in this session. That is a result about "
            "these questions, not about the competency as a whole — one "
            "interview is a handful of observations."
        )
    if not coaching.practice:
        coaching.practice.append(
            "Take the same interview against a more senior target role to find "
            "where the ceiling actually is."
        )

    return coaching


def _speech_observations(report: dict) -> list[str]:
    """Delivery hints, explicitly framed as delivery."""
    out: list[str] = []
    wpms, filler_rates, long_pauses = [], [], 0

    for answer in report.get("answers") or []:
        metrics = answer.get("metrics") or {}
        if metrics.get("wpm"):
            wpms.append(metrics["wpm"])
        if metrics.get("filler_rate") is not None:
            filler_rates.append(metrics["filler_rate"])
        long_pauses += metrics.get("long_pause_count") or 0

    if wpms:
        mean_wpm = sum(wpms) / len(wpms)
        if mean_wpm > FAST_WPM:
            out.append(
                f"You averaged {mean_wpm:.0f} words a minute, which is quick. "
                "Slowing down mainly helps the listener, not the score."
            )
        elif mean_wpm < SLOW_WPM:
            out.append(
                f"You averaged {mean_wpm:.0f} words a minute. That is unhurried, "
                "which is fine — it is only worth noting if you ran out of time."
            )

    if filler_rates:
        mean_filler = sum(filler_rates) / len(filler_rates)
        if mean_filler > HIGH_FILLER_RATE:
            out.append(
                f"Filler words ran at {mean_filler:.1f} per 100 words. Fillers "
                "usually mark where the answer was still being planned, so "
                "deciding your first sentence before you start is what reduces them."
            )

    if long_pauses >= LONG_PAUSE_CONCERN:
        out.append(
            f"There were {long_pauses} long pauses across the session. A pause "
            "while you think is fine; this is only worth noticing if you felt "
            "stuck rather than considering."
        )

    return out


def _weakest_raw(report: dict) -> list[tuple[int, str, float]]:
    per_competency: dict[int, tuple[str, list[float]]] = {}
    for answer in report.get("answers") or []:
        cid = answer.get("competency_id")
        scores = answer.get("scores") or {}
        knowledge = scores.get("knowledge")
        if cid is None or knowledge is None:
            continue
        name, values = per_competency.get(cid, (answer.get("competency") or "", []))
        values.append(knowledge)
        per_competency[cid] = (name, values)

    ranked = [
        (cid, name, sum(values) / len(values))
        for cid, (name, values) in per_competency.items() if values
    ]
    return sorted(ranked, key=lambda row: row[2])

