"""initial schema

Revision ID: 35bba1d55080
Revises: 
Create Date: 2026-09-08 00:10:22.526805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35bba1d55080'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Course and chunk embeddings are pgvector columns, so the extension has to
    # exist before the tables that use it. Nothing else in the chain creates it:
    # `init_db()` does, but a deployment that only runs migrations never calls
    # that.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('domain', sa.Enum('STATISTICAL', 'TECHNICAL', 'DIGITAL_GOVERNANCE', 'BEHAVIOURAL', name='competency_domain', native_enum=False), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competencies_code'), 'competencies', ['code'], unique=True)
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_code'), 'divisions', ['code'], unique=True)
    op.create_table('frac_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('grade', sa.String(length=48), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('min_service_years', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_frac_roles_code'), 'frac_roles', ['code'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('IGOT', 'NSSTA', 'EXTERNAL', 'INTERNAL', name='course_source', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('level_from', sa.Float(), nullable=False),
    sa.Column('level_to', sa.Float(), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_course_source_external')
    )
    op.create_index('ix_course_competency', 'courses', ['competency_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('frac_role_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('expected_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bloom_level', sa.String(length=24), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_baseline', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_from_answer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['frac_role_id'], ['frac_roles.id'], ),
    # fk_question_generated_from_answer is added after this table, by an
    # ALTER at the end of this migration: it closes a cycle with
    # interview_answers, so it cannot exist at table-creation time.
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_competency_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frac_role_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('required_level', sa.Float(), nullable=False),
    sa.Column('criticality', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='criticality', native_enum=False), nullable=False),
    sa.CheckConstraint('required_level >= 1 AND required_level <= 5', name='ck_required_level_range'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['frac_role_id'], ['frac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frac_role_id', 'competency_id', name='uq_role_competency')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('role', sa.Enum('LEARNER', 'SUPERVISOR', 'SME', 'ADMIN', name='user_role', native_enum=False), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('frac_role_id', sa.Integer(), nullable=True),
    sa.Column('service_years', sa.Float(), nullable=False),
    sa.Column('baseline_wpm', sa.Float(), nullable=True),
    sa.Column('baseline_filler_rate', sa.Float(), nullable=True),
    sa.Column('fluency_scoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['frac_role_id'], ['frac_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=True),
    sa.Column('entity_id', sa.String(length=60), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('competency_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('evidence_weight', sa.Float(), nullable=False),
    sa.Column('strongest_source', sa.Enum('SIMULATION', 'QUIZ', 'DIAGNOSTIC', 'INTERVIEW', 'LEARNING_ACTIVITY', 'CERTIFICATION', 'SUPERVISOR', 'HISTORICAL', 'SELF', name='evidence_source', native_enum=False), nullable=True),
    sa.Column('last_evidence_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'competency_id', name='uq_profile_user_competency')
    )
    op.create_index(op.f('ix_competency_profile_user_id'), 'competency_profile', ['user_id'], unique=False)
    op.create_table('course_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('level_at_completion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_completion')
    )
    op.create_index(op.f('ix_course_completions_course_id'), 'course_completions', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_completions_user_id'), 'course_completions', ['user_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('requires_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'requires_id', name='uq_prerequisite')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CALIBRATING', 'IN_PROGRESS', 'ANALYSING', 'COMPLETED', 'ABANDONED', name='interview_status', native_enum=False), nullable=False),
    sa.Column('baseline_wpm', sa.Float(), nullable=True),
    sa.Column('baseline_filler_rate', sa.Float(), nullable=True),
    sa.Column('fluency_scoring_enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('is_adaptive', sa.Boolean(), nullable=False),
    sa.Column('max_questions', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['target_role_id'], ['frac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviews_user_id'), 'interviews', ['user_id'], unique=False)
    op.create_table('learning_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('target_level', sa.Float(), nullable=False),
    sa.Column('reaches_level', sa.Float(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('estimated_weeks', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['frac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_paths_user_id'), 'learning_paths', ['user_id'], unique=False)
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADED', 'EXTRACTING', 'READY', 'FAILED', name='material_status', native_enum=False), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proficiency_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('level_estimate', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('SIMULATION', 'QUIZ', 'DIAGNOSTIC', 'INTERVIEW', 'LEARNING_ACTIVITY', 'CERTIFICATION', 'SUPERVISOR', 'HISTORICAL', 'SELF', name='evidence_source', native_enum=False), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_evidence_confidence_range'),
    sa.CheckConstraint('level_estimate >= 1 AND level_estimate <= 5', name='ck_evidence_level_range'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_user_competency', 'proficiency_evidence', ['user_id', 'competency_id'], unique=False)
    op.create_index(op.f('ix_proficiency_evidence_created_at'), 'proficiency_evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_proficiency_evidence_user_id'), 'proficiency_evidence', ['user_id'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'ABANDONED', name='attempt_status', native_enum=False), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('mean_difficulty', sa.Float(), nullable=True),
    sa.Column('derived_level', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempt_user_competency', 'quiz_attempts', ['user_id', 'competency_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('target_role_id', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('required_level', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_role_id'], ['frac_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_user_competency', 'recommendations', ['user_id', 'competency_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('interview_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECORDED', 'TRANSCRIBED', 'ANALYSING', 'SCORED', 'FAILED', name='answer_status', native_enum=False), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript_raw', sa.Text(), nullable=True),
    sa.Column('transcript_confirmed', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('asked_because', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_answers_interview_id'), 'interview_answers', ['interview_id'], unique=False)
    op.create_table('material_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_material_ordinal', 'material_chunks', ['material_id', 'ordinal'], unique=False)
    op.create_index(op.f('ix_material_chunks_material_id'), 'material_chunks', ['material_id'], unique=False)
    op.create_table('path_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'AVAILABLE', 'IN_PROGRESS', 'COMPLETED', name='path_item_status', native_enum=False), nullable=False),
    sa.Column('included_because', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['path_id'], ['learning_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('words', sa.Integer(), nullable=False),
    sa.Column('wpm', sa.Float(), nullable=True),
    sa.Column('articulation_rate', sa.Float(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('filler_rate', sa.Float(), nullable=True),
    sa.Column('fillers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('long_pause_count', sa.Integer(), nullable=False),
    sa.Column('mean_pause_seconds', sa.Float(), nullable=True),
    sa.Column('latency_to_first_word', sa.Float(), nullable=True),
    sa.Column('pause_spans', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pitch_mean', sa.Float(), nullable=True),
    sa.Column('pitch_sd', sa.Float(), nullable=True),
    sa.Column('intensity_mean', sa.Float(), nullable=True),
    sa.Column('jitter', sa.Float(), nullable=True),
    sa.Column('hedge_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_table('answer_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('knowledge', sa.Float(), nullable=False),
    sa.Column('knowledge_confidence', sa.Float(), nullable=False),
    sa.Column('structure', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('covered_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missed_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('judged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('knowledge >= 1 AND knowledge <= 5', name='ck_knowledge_range'),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_table('attention_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('screen_gaze_ratio', sa.Float(), nullable=True),
    sa.Column('longest_look_away_seconds', sa.Float(), nullable=True),
    sa.Column('look_away_count', sa.Integer(), nullable=True),
    sa.Column('blink_rate_per_minute', sa.Float(), nullable=True),
    sa.Column('head_stability', sa.Float(), nullable=True),
    sa.Column('face_present_ratio', sa.Float(), nullable=True),
    sa.Column('frames_analysed', sa.Integer(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('consent_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attention_metrics_answer_id'), 'attention_metrics', ['answer_id'], unique=True)
    op.create_table('generated_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('MCQ', 'NUMERICAL', 'SCENARIO', name='question_kind', native_enum=False), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('distractor_rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('bloom_level', sa.String(length=24), nullable=False),
    sa.Column('citation_chunk_id', sa.Integer(), nullable=True),
    sa.Column('citation_quote', sa.Text(), nullable=True),
    sa.Column('citation_page', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', 'RETIRED', name='question_status', native_enum=False), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_by_model', sa.String(length=80), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('times_attempted', sa.Integer(), nullable=False),
    sa.Column('times_correct', sa.Integer(), nullable=False),
    sa.Column('difficulty_p', sa.Float(), nullable=True),
    sa.Column('discrimination', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('correct_index >= 0 AND correct_index <= 5', name='ck_correct_index_range'),
    sa.ForeignKeyConstraint(['citation_chunk_id'], ['material_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_questions_material_id'), 'generated_questions', ['material_id'], unique=False)
    op.create_index('ix_question_status_competency', 'generated_questions', ['status', 'competency_id'], unique=False)
    op.create_table('item_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('selected_index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('seconds_taken', sa.Float(), nullable=True),
    sa.Column('option_order', sa.String(length=40), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('selected_index >= 0', name='ck_selected_index'),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['generated_questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_response_per_item')
    )
    op.create_index(op.f('ix_item_responses_attempt_id'), 'item_responses', ['attempt_id'], unique=False)
    op.create_index('ix_response_question', 'item_responses', ['question_id'], unique=False)
    # ### end Alembic commands ###

    # The cycle-closing constraint: an answer points at its question, and a
    # question the model generated points back at the answer that provoked it.
    op.create_foreign_key(
        'fk_question_generated_from_answer', 'interview_questions',
        'interview_answers', ['generated_from_answer_id'], ['id'],
        ondelete='SET NULL',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_question_generated_from_answer', 'interview_questions',
                       type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_response_question', table_name='item_responses')
    op.drop_index(op.f('ix_item_responses_attempt_id'), table_name='item_responses')
    op.drop_table('item_responses')
    op.drop_index('ix_question_status_competency', table_name='generated_questions')
    op.drop_index(op.f('ix_generated_questions_material_id'), table_name='generated_questions')
    op.drop_table('generated_questions')
    op.drop_index(op.f('ix_attention_metrics_answer_id'), table_name='attention_metrics')
    op.drop_table('attention_metrics')
    op.drop_table('answer_scores')
    op.drop_table('answer_metrics')
    op.drop_table('path_items')
    op.drop_index(op.f('ix_material_chunks_material_id'), table_name='material_chunks')
    op.drop_index('ix_chunk_material_ordinal', table_name='material_chunks')
    op.drop_table('material_chunks')
    op.drop_index(op.f('ix_interview_answers_interview_id'), table_name='interview_answers')
    op.drop_table('interview_answers')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index('ix_recommendation_user_competency', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index('ix_attempt_user_competency', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_proficiency_evidence_user_id'), table_name='proficiency_evidence')
    op.drop_index(op.f('ix_proficiency_evidence_created_at'), table_name='proficiency_evidence')
    op.drop_index('ix_evidence_user_competency', table_name='proficiency_evidence')
    op.drop_table('proficiency_evidence')
    op.drop_table('materials')
    op.drop_index(op.f('ix_learning_paths_user_id'), table_name='learning_paths')
    op.drop_table('learning_paths')
    op.drop_index(op.f('ix_interviews_user_id'), table_name='interviews')
    op.drop_table('interviews')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_course_completions_user_id'), table_name='course_completions')
    op.drop_index(op.f('ix_course_completions_course_id'), table_name='course_completions')
    op.drop_table('course_completions')
    op.drop_index(op.f('ix_competency_profile_user_id'), table_name='competency_profile')
    op.drop_table('competency_profile')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_competency_requirements')
    op.drop_table('interview_questions')
    op.drop_index('ix_course_competency', table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_frac_roles_code'), table_name='frac_roles')
    op.drop_table('frac_roles')
    op.drop_index(op.f('ix_divisions_code'), table_name='divisions')
    op.drop_table('divisions')
    op.drop_index(op.f('ix_competencies_code'), table_name='competencies')
    op.drop_table('competencies')
    # ### end Alembic commands ###
