"""irt item parameters and adaptive attempt state

Puts items and people on one scale so the assessment can choose what to ask
next instead of serving a fixed list.

The backfill at the end is the part that matters. Adding these columns with
their defaults would leave every existing item at ``irt_b = 0.0`` — difficulty
exactly L3, identical across the whole bank — and an adaptive test over a bank
with no difficulty spread silently degrades into a random one. Nothing would
error; the assessment would simply stop adapting. So existing rows are seeded
from the Bloom level their author already gave them, which is a statement about
cognitive demand and the best prior available without re-reading every item.

Revision ID: 5a74dbf2113a
Revises: c844b8c09527
Create Date: 2026-09-15 19:06:17.722320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a74dbf2113a'
down_revision: Union[str, Sequence[str], None] = 'c844b8c09527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('generated_questions', sa.Column('irt_a', sa.Float(), server_default='1.3', nullable=False))
    op.add_column('generated_questions', sa.Column('irt_b', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('generated_questions', sa.Column('irt_b_authored', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('generated_questions', sa.Column('irt_c', sa.Float(), server_default='0.25', nullable=False))
    op.add_column('generated_questions', sa.Column('irt_sample_size', sa.Integer(), server_default='0', nullable=False))
    op.add_column('generated_questions', sa.Column('irt_calibrated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('item_responses', sa.Column('theta_before', sa.Float(), nullable=True))
    op.add_column('item_responses', sa.Column('theta_after', sa.Float(), nullable=True))
    op.add_column('item_responses', sa.Column('se_after', sa.Float(), nullable=True))
    op.add_column('item_responses', sa.Column('item_information', sa.Float(), nullable=True))
    op.add_column('item_responses', sa.Column('item_difficulty', sa.Float(), nullable=True))
    op.add_column('item_responses', sa.Column('asked_because', sa.Text(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('is_adaptive', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('quiz_attempts', sa.Column('theta', sa.Float(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('theta_se', sa.Float(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('stop_reason', sa.String(length=24), nullable=True))
    # ### end Alembic commands ###

    # --- backfill ---------------------------------------------------------- #
    # Bloom level -> difficulty on the L1-L5 axis -> theta, where L3 is theta 0
    # and one theta is two-thirds of a level. Written out as literals rather
    # than importing app.ml.irt: a migration has to keep producing the same
    # schema years from now, and a constant that moves in application code
    # would silently change what this revision did.
    op.execute("""
        UPDATE generated_questions SET irt_b = CASE lower(coalesce(bloom_level, ''))
            WHEN 'remember'   THEN -1.50
            WHEN 'understand' THEN -0.60
            WHEN 'apply'      THEN  0.45
            WHEN 'analyse'    THEN  1.35
            WHEN 'analyze'    THEN  1.35
            WHEN 'evaluate'   THEN  2.10
            WHEN 'create'     THEN  2.70
            ELSE 0.0
        END
    """)
    op.execute("UPDATE generated_questions SET irt_b_authored = irt_b")

    # The guessing floor is 1/options. An item with no options stored is not
    # servable anyway; 0.25 is the safe reading for anything unexpected.
    op.execute("""
        UPDATE generated_questions
           SET irt_c = CASE
               WHEN jsonb_array_length(options) BETWEEN 2 AND 6
               THEN 1.0 / jsonb_array_length(options)
               ELSE 0.25
           END
    """)

    # Attempts taken under the fixed form are marked as such, so the history
    # table does not present them as adaptive results they never were.
    op.execute("UPDATE quiz_attempts SET is_adaptive = false")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_attempts', 'stop_reason')
    op.drop_column('quiz_attempts', 'theta_se')
    op.drop_column('quiz_attempts', 'theta')
    op.drop_column('quiz_attempts', 'is_adaptive')
    op.drop_column('item_responses', 'asked_because')
    op.drop_column('item_responses', 'item_difficulty')
    op.drop_column('item_responses', 'item_information')
    op.drop_column('item_responses', 'se_after')
    op.drop_column('item_responses', 'theta_after')
    op.drop_column('item_responses', 'theta_before')
    op.drop_column('generated_questions', 'irt_calibrated_at')
    op.drop_column('generated_questions', 'irt_sample_size')
    op.drop_column('generated_questions', 'irt_c')
    op.drop_column('generated_questions', 'irt_b_authored')
    op.drop_column('generated_questions', 'irt_b')
    op.drop_column('generated_questions', 'irt_a')
    # ### end Alembic commands ###
