"""Role-based competency simulation: authored scenarios and scored attempts.

Two tables. `scenarios` holds the authored situations and their rubrics;
`simulation_attempts` holds what an officer wrote and how it scored on five
axes. Only two of those axes become competency evidence — see
`app/models_simulation.py` for why.

Revision ID: ba499a754564
Revises: 3e0074a4bd83
Create Date: 2026-09-28 19:13:22.883817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba499a754564'
down_revision: Union[str, Sequence[str], None] = '3e0074a4bd83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('competency_id', sa.Integer(), nullable=False),
    sa.Column('situation', sa.Text(), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('constraint', sa.Text(), nullable=True),
    sa.Column('expected_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('common_traps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_level', sa.Float(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_scenarios_competency_id'), 'scenarios', ['competency_id'], unique=False)
    op.create_table('simulation_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'SCORED', 'ABANDONED', name='simulation_status'), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Float(), nullable=True),
    sa.Column('prioritisation', sa.Float(), nullable=True),
    sa.Column('communication', sa.Float(), nullable=True),
    sa.Column('decision_making', sa.Float(), nullable=True),
    sa.Column('derived_level', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('covered_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missed_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('traps_hit', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=80), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_attempts_scenario_id'), 'simulation_attempts', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_simulation_attempts_user_id'), 'simulation_attempts', ['user_id'], unique=False)
    op.create_index('ix_simulation_user_scenario', 'simulation_attempts', ['user_id', 'scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_simulation_user_scenario', table_name='simulation_attempts')
    op.drop_index(op.f('ix_simulation_attempts_user_id'), table_name='simulation_attempts')
    op.drop_index(op.f('ix_simulation_attempts_scenario_id'), table_name='simulation_attempts')
    op.drop_table('simulation_attempts')
    op.drop_index(op.f('ix_scenarios_competency_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###

    # Autogenerate creates the enum type with the table and forgets to drop it.
    # Left behind, the next `upgrade` fails with DuplicateObject on a database
    # that has been downgraded — which is exactly when someone is least able to
    # debug it.
    sa.Enum(name="simulation_status").drop(op.get_bind(), checkfirst=True)
