"""interview mistakes and gesture aggregates

Revision ID: bf8d038fa416
Revises: c844b8c09527
Create Date: 2026-09-14 23:48:57.644970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf8d038fa416'
down_revision: Union[str, Sequence[str], None] = 'c844b8c09527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer_scores', sa.Column('mistakes', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('attention_metrics', sa.Column('hands_visible_ratio', sa.Float(), nullable=True))
    op.add_column('attention_metrics', sa.Column('hand_movement', sa.Float(), nullable=True))
    op.add_column('attention_metrics', sa.Column('face_touch_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attention_metrics', 'face_touch_count')
    op.drop_column('attention_metrics', 'hand_movement')
    op.drop_column('attention_metrics', 'hands_visible_ratio')
    op.drop_column('answer_scores', 'mistakes')
    # ### end Alembic commands ###
